pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                bat './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                script {
                    // Run the delivery script
                    bat 'jenkins\\scripts\\deliver.bat'

                    // Wait for user input
                    input message: 'Finished using the web site? (Click "Proceed" to continue)'

                    // Run the kill script
                    bat 'jenkins\\scripts\\kill.bat'
                }
            }
        }
    }
}
